name: release

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
    branches:
      - master
      - next

concurrency:
  group: "release-${{ github.ref_name }}"
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: "https://registry.npmjs.org/"
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm ci

      - name: version calculation
        id: version
        run: node scripts/version.ts

      - name: version bump
        run: npm version --no-git-tag-version "${{steps.version.outputs.NEW_VERSION}}"

      - name: version commit
        uses: EndBug/add-and-commit@v9
        with:
          add: package.json package-lock.json
          message: "misc: release v${{ steps.version.outputs.NEW_VERSION }}"
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com

      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.NEW_VERSION }}
          target_commitish: ${{ github.event.workflow_run.head_branch }}
          prerelease: ${{ github.event.workflow_run.head_branch == 'next' }}
          body: ${{ steps.version.outputs.RELEASE_BODY }}

      - if: github.event.workflow_run.head_branch == 'master'
        run: npm publish

      - if: github.event.workflow_run.head_branch == 'next'
        run: npm publish --tag next
