name: release

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
    branches:
      - master
      - next

concurrency:
  group: "release-${{ github.ref_name }}"
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: auto_command
        id: auto_command
        run: |
          BRANCH=${{ github.event.workflow_run.head_branch }}
          if [ "$BRANCH" == "master" ]; then
            echo "command=latest" >> $GITHUB_OUTPUT
          else
            echo "command=next" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: "https://registry.npmjs.org/"
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm ci

      - uses: mxschmitt/action-tmate@v3

      - run: npx auto ${{ steps.auto_command.outputs.command }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
